apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iko.fullname" . }}
  labels:
    {{- include "iko.labels" . | nindent 4 }}
data:
  # Spring Boot configuratie
  SERVER_PORT: {{ .Values.settings.iko.serverPort | quote }}

  {{- if .Values.settings.management.enabled }}
  # Spring Boot Actuator / management configuratie
  MANAGEMENT_SERVER_PORT: {{ .Values.settings.management.port | quote }}
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,prometheus"
  {{- end }}

  # Database configuratie
  SPRING_DATASOURCE_URL: {{ .Values.settings.spring.datasource.url | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.settings.spring.datasource.username | quote }}
  SPRING_DATASOURCE_DRIVERCLASSNAME: {{ .Values.settings.spring.datasource.driverClassName | quote }}
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: {{ .Values.settings.spring.jpa.properties.hibernateDialect | quote }}

  # OAuth2 en Security configuratie
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUERURI: {{ printf "%s/realms/%s" .Values.settings.keycloak.authServerURL .Values.settings.keycloak.realm | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTID: {{ .Values.settings.keycloak.clientID | quote }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI: {{ printf "%s/realms/%s" .Values.settings.keycloak.authServerURL .Values.settings.keycloak.realm | quote }}
  IKO_SECURITY_ADMIN_ROLESCLAIM: {{ .Values.settings.iko.security.admin.rolesClaim | quote }}
  IKO_SECURITY_ADMIN_AUTHORITIES: {{ .Values.settings.iko.security.admin.authorities | quote }}
  IKO_SECURITY_ADMIN_SESSION_TIMEOUT: {{ .Values.settings.iko.security.admin.session.timeout | quote }}
  IKO_SECURITY_ADMIN_SESSION_WARNINGBEFORE: {{ .Values.settings.iko.security.admin.session.warningBefore | quote }}
  SERVER_SERVLET_SESSION_COOKIE_SECURE: {{ .Values.settings.iko.security.sessionCookieSecure | quote }}

  # Logging configuratie
  IKO_LOGGING_RETENTION: {{ .Values.settings.iko.logging.retention | quote }}
  IKO_LOGGING_DELETIONCRON: {{ .Values.settings.iko.logging.deletionCron | quote }}
  IKO_LOGGING_DB_ENABLED: {{ .Values.settings.iko.logging.enabled | quote }}

  SPRING_DATA_REDIS_HOST: {{- if .Values.redis.enabled }}
    {{ printf "%s-redis" (include "iko.fullname" .) | quote }}
  {{- else }}
    {{ .Values.settings.redis.host | quote }}
  {{- end }}
  
  SPRING_DATA_REDIS_PORT: {{- if .Values.redis.enabled }}
    {{ .Values.redis.service.port | quote }}
  {{- else }}
    {{ .Values.settings.redis.port | quote }}
  {{- end }}
